// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQOJZ-bFUwViRjJrYfprTv1K-a_U9EfiU',
    appId: '1:963263552483:web:6a0f57cc6858d56d2b1ed6',
    messagingSenderId: '963263552483',
    projectId: 'tracking-a140b',
    authDomain: 'tracking-a140b.firebaseapp.com',
    storageBucket: 'tracking-a140b.appspot.com',
    measurementId: 'G-YN1BCLBHFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcJqlPQAhQP1-KbPHyDZxBIuysWKWUF8',
    appId: '1:963263552483:android:0962f7cfdbeb0f832b1ed6',
    messagingSenderId: '963263552483',
    projectId: 'tracking-a140b',
    storageBucket: 'tracking-a140b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXb4F7Sdz7eiswTrS7KZ6o6tGU7XWBXZY',
    appId: '1:963263552483:ios:f5aa44d9c4dffa1c2b1ed6',
    messagingSenderId: '963263552483',
    projectId: 'tracking-a140b',
    storageBucket: 'tracking-a140b.appspot.com',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXb4F7Sdz7eiswTrS7KZ6o6tGU7XWBXZY',
    appId: '1:963263552483:ios:f5aa44d9c4dffa1c2b1ed6',
    messagingSenderId: '963263552483',
    projectId: 'tracking-a140b',
    storageBucket: 'tracking-a140b.appspot.com',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQOJZ-bFUwViRjJrYfprTv1K-a_U9EfiU',
    appId: '1:963263552483:web:2ae1e8c6c66038fa2b1ed6',
    messagingSenderId: '963263552483',
    projectId: 'tracking-a140b',
    authDomain: 'tracking-a140b.firebaseapp.com',
    storageBucket: 'tracking-a140b.appspot.com',
    measurementId: 'G-CHWTQEFX6Y',
  );
}
